test run to update to Gatsby 5
postmanlabs/covid-19-apis pull request #376
Opened 2023-02-15 18:36 UTC by ch264

2023-02-15 19:20 UTC, brandonmcastillo approved these changes

2023-02-16 19:42 UTC, tristandenyer requested changes

2023-02-16 19:42 UTC, tristandenyer commented on gatsby-config.js
> +    // {
@ch264 can you source a new package / plugin that will work with this + GA4? We ar eusing this site to test out the GA4 upgrade, and it needs to keep working.

2023-02-17 00:14 UTC, tristandenyer approved these changes

2025-01-23 10:01 UTC, ch264 commented
This app is now deprecated

2025-01-23 10:01 UTC, closed without merging